### ISSUE TITLE
floating json script viewer

### ISSUE THREAD

**Issue by rlzijdeman** [CLARIAH/ruminator#4]
Hi currently the script viewer (on the right hand side) has fixed position on the page. This is problematic if you scroll down to work on variables  at the bottom of the page (at the left hand side). It would be optimal if the script viewer would float on the page.

A really cool option (but prolly out of scope) is to highlight in the script viewer on which variable your are working (on the left hand side).

**Comment by mmmenno** [comment]
Both json (in the right pane) and form (on the left) are positioned absolute now, so you can scroll each independently, always keeping both in sight.

It's difficult to highlight variables you're working on, because the json is nothing more then a large string that is written anew each time you press the 'create json from form' button. What i did do, is check the position of the jsonviewer before renewing the json, and then scroll to that position after renewing. I hope you're happy with that solution @rlzijdeman and if not i'm sure you will reopen this issue ;-)
